# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "FluidAudio" = "sha256-/KTcZLu4G7W+NAOIKLi+SRDq4IpuRw+wwxdTDyPQ2hE=";
    "swift-argument-parser" = "sha256-BWm2ZbNIvlamNp8cxoicFlAcujjhH22VPzs67lEIXWU=";
  };
}
